services:
  - type: web
    name: ats-project
    env: python
    pythonVersion: 3.11
    rootDir: .
    buildCommand: bash render-build.sh
    startCommand: bash render-start.sh
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: .onrender.com,localhost,127.0.0.1
      - key: GOOGLE_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
