# Generated by Django 5.2.5 on 2026-06-10 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_jobfield_job_application"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="ats_feedback",
            field=models.TextField(blank=True, null=True),
        ),
    ]
